### ISSUE TITLE
static rendering for individual documents

### ISSUE THREAD

**Issue by mirrir0** [mycorrhiza-inc/kessler#164]

**Comment by cappuccinocosmico** [comment]
Shitty Idea Time:
all proceedings pages are dynamically generated

The Backend go/python know all of the documents, and therefore can generate a list of all the URLs for the documents

A program goes ahead and slowly visits every webpage, gets the HTML from next, stores it in a file.

Nginx serves those files

When new files are added the program only needs to walk over the new files

**Comment by cappuccinocosmico** [comment]
Did a version of this, the html is statically generated by go without ever touching the frontend
