### ISSUE TITLE
Organization pages taking a long time to load

### ISSUE THREAD

**Issue by jpvelez** [mycorrhiza-inc/kessler#292]
https://ny.kessler.xyz/orgs/800b9878-8193-4064-877f-0259a3db10e8

Not sure if it actually loads, because I stopped waiting after a minute

**Comment by cappuccinocosmico** [comment]
According to my analysis, it seems that it doesnt retrieve any documents. This seems to be a seperate problem of organization pages not loading any docs dispite docs clearly being provided. But breaking the UI Bug into a seperate issue.
