### ISSUE TITLE
Org Pages are showing documents from all authors

### ISSUE THREAD

**Issue by cappuccinocosmico** [mycorrhiza-inc/kessler#295]

**Comment by cappuccinocosmico** [comment]
https://ny.kessler.xyz/orgs/800b9878-8193-4064-877f-0259a3db10e8
![image](https://github.com/user-attachments/assets/3d7adfa4-5745-4ace-8110-20034c03e74e)

**Comment by cappuccinocosmico** [comment]
Well it turns out that in the midst of a migration this entire component was thrown in the garbage, I did replace it with a new error for some orgs that shows up as identical behavior, but that is much more solvable

**Comment by cappuccinocosmico** [comment]
on the plus side, documents are showing up, but they arent actually doing any filters yay!
![image](https://github.com/user-attachments/assets/336182c5-58c0-40a2-9c40-04b091bf2ae9)

**Comment by cappuccinocosmico** [comment]
![image](https://github.com/user-attachments/assets/4bc211cd-7278-40e9-9867-a10d0fe7f4ac)
main thing here is to use the author UUIDs

**Comment by mirrir0** [comment]
Fixed in #310
